### ISSUE TITLE
error compil and zig 0.14 dev 1391

### ISSUE THREAD

**Issue by AS400JPLPC** [andrewCodeDev/Fluent#20]
fluent.zig:1651:10: error: no field named 'Pointer' in enum '@typeInfo(builtin.Type).@"union".tag_type.?'
        .Pointer => |ptr| return ptr.is_const,
        
        
fluent.zig:1723:10: error: no field named 'Array' in enum '@typeInfo(builtin.Type).@"union".tag_type.?'
        .Array => |a| a.child,
        ~^~~~~
.zig/lib/std/builtin.zig:259:18: note: enum declared here
pub const Type = union(enum) {

**Comment by andrewCodeDev** [comment]
Fixing the issue is relatively straightforward. They have renamed all their builtin types that `@typeInfo` returns to be lowercase. I don't want to push this to the main branch because it will break all code for 0.13 while 0.14 is still under construction: https://github.com/ziglang/zig/milestone/20

In the mean time, I have opened a branch for 0.14 - you can pull from this branch instead. When 0.14 becomes standard, I will merge this new branch into main.

Use this branch if you want to have 14.0 compatibility:: https://github.com/andrewCodeDev/Fluent/tree/zig-0.14-version
